version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:5000"
    container_name: api
  session:
    image: "redis:alpine"
    command: redis-server --port 6379 --requirepass  ${SESSION_PASS}
    expose:
      - "6379"
    container_name: session
  db:
    image: "redis:alpine"
    command: redis-server --port 6380 --requirepass  ${DB_PASS}
    expose:
      - "6380"
    container_name: db
