site_name: Covid Tracker

repo_url: https://github.com/rory652/3881-project/
repo_name: rory652/3881-project

edit_uri: ""

theme:
  name: material
  logo: img/icon.png
  favicon: img/icon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: deep purple
    accent: purple
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - navigation.indexes

nav:
  - Home: index.md
  - Reference: 
      - reference/index.md
  - About: 
      - about/index.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
